project_id = "akdlvhfrslztmhsiurqo"

[functions.generate-agent]
verify_jwt = false

[functions.generate-workflow]
verify_jwt = false

[functions.workflow-advisor]
verify_jwt = false

[functions.generate-code]
verify_jwt = false

[functions.realtime-token]
verify_jwt = false

[functions.deploy-project]
verify_jwt = false

[functions.run-sandbox]
verify_jwt = false

[functions.autofix-code]
verify_jwt = false

[functions.edit-project]
verify_jwt = false

[functions.manage-secrets]
verify_jwt = false
